site_name: Predicting Cancer Drug Response (CDR) using Graph Neural Networks (GNN)
theme: readthedocs
highlightjs: True
collapse_navigation: True 
navigation_depth: 4
sticky_navigation: True 
locale: en
include_homepage_in_sidebar: True
copyright: Copyright &copy; 2021 Nate Evans

nav:
- 'Home': index.md
- 'Synthetic Data': 
  - 'Generating a Synthetic Dataset': ./01_synth_data/generation.md
  - 'The Synthetic gnnCDR Data Object': ./01_synth_data/data_obj.md
  - 'Creating Train/Test/Val Datasets': ./01_synth_data/data_split.md
- 'Model Architecture': 
  - 'gnnCDR': ./02_model/gnnCDR_arch.md
  - 'naiveNN': ./02_model/naiveNN_arch.md

- 'User Guide': 
  - 'Mkdocs Help': pages_usage/mkdocs_guides.md
  - 'Mkdocs Syntax': pages_usage/syntax_examples.md

extra_javascript: 
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - javascripts/mathjax.js


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  
plugins:
      - search
      - mkdocstrings
      - table-reader
