site_name: Predicting Cancer Drug Response (CDR) using Graph Neural Networks (GNN)
theme: readthedocs
highlightjs: True
collapse_navigation: True 
navigation_depth: 4
sticky_navigation: True 
locale: en
include_homepage_in_sidebar: True
copyright: Copyright &copy; 2021 Nate Evans

nav:
- 'Home': index.md
- 'Motivation': motivation.md
- 'Problem Overview': problem_overview.md
- 'Synthetic Data': 
  - 'Generating a Synthetic Dataset': ./01_synth_data/generation.md
  - 'The Synthetic gnnCDR Data Object': ./01_synth_data/data_obj.md
  - 'Creating Train/Test/Val Datasets': ./01_synth_data/data_split.md
- 'Real Data':
  - 'Creating a Global Graph': 
    - 'Functional Interaction Network': ./02_real_data/fi_graph.md
    - 'Drug-Target Interaction Network': ./02_real_data/dti_graph.md
  - 'Exogenous Features': 
    - 'Overview': ./02_real_data/overview.md
    - 'Expression': ./02_real_data/expression.md
    - 'Mutation': ./02_real_data/mutation.md
    - 'Copy Number Variation (CNV)': ./02_real_data/cnv.md
    - 'Methylation': ./02_real_data/methylation.md
    - 'Gene Dependency': ./02_real_data/gene_dep.md
- 'Model Architecture': 
  - 'gnnCDR': ./03_model/gnnCDR_arch.md
  - 'naiveNN': ./03_model/naiveNN_arch.md
  - 'Choice of Target and Metrics': './03_model/targets_and_metrics.md'  
  - 'PPI trainable edge weights': './03_model/ppi_context_edge_weight_decay.md'

- 'User Guide': 
  - 'Mkdocs Help': pages_usage/mkdocs_guides.md
  - 'Mkdocs Syntax': pages_usage/syntax_examples.md

extra_javascript: 
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - javascripts/mathjax.js


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  
plugins:
      - search
      - mkdocstrings
      - table-reader
